### ISSUE TITLE
Consumer Error that does not look like connection failure. IOError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by imanassypov** [Cisco-AMP/amp4e_splunk_events_input#8] opened 2018-09-22 19:02 UTC
Hi,

I am not getting any events registered on my splunk appliance. Looking at the plugin log, I can see a random occurrence of the following:

2018-09-17 04:22:09,062 WARNING Amp4eEvents - Connection error (1537176129.06, <class 'pika.exceptions.ConnectionClosed'>: The AMQP connection was closed: ())! Reconnecting in about 3 seconds

2018-09-17 06:42:16,745 ERROR Amp4eEvents - Consumer Error that does not look like connection failure! See the traceback below.
2018-09-17 06:42:16,747 ERROR Amp4eEvents - Traceback (most recent call last):
  File "/opt/splunk/etc/apps/amp4e_events_input/bin/util/stream_consumer.py", line 30, in run
    self.start_consuming()
  File "/opt/splunk/etc/apps/amp4e_events_input/bin/util/stream_consumer.py", line 57, in start_consuming
    self._channel.start_consuming()
  File "/opt/splunk/etc/apps/amp4e_events_input/bin/pika/adapters/blocking_connection.py", line 1681, in start_consuming
    self.connection.process_data_events(time_limit=None)
  File "/opt/splunk/etc/apps/amp4e_events_input/bin/pika/adapters/blocking_connection.py", line 656, in process_data_events
    self._dispatch_channel_events()
  File "/opt/splunk/etc/apps/amp4e_events_input/bin/pika/adapters/blocking_connection.py", line 469, in _dispatch_channel_events
    impl_channel._get_cookie()._dispatch_events()
  File "/opt/splunk/etc/apps/amp4e_events_input/bin/pika/adapters/blocking_connection.py", line 1310, in _dispatch_events
    evt.body)
  File "/opt/splunk/etc/apps/amp4e_events_input/bin/util/stream_consumer.py", line 61, in on_message
    self.on_event_callback(body)
  File "/opt/splunk/etc/apps/amp4e_events_input/bin/amp4e_events_input.py", line 56, in <lambda>
    'index': stream.get('index')}))
  File "/opt/splunk/etc/apps/amp4e_events_input/bin/amp4e_events_input.py", line 91, in __on_event_callback
    ew.write_event(event)
  File "/opt/splunk/etc/apps/amp4e_events_input/bin/splunklib/modularinput/event_writer.py", line 60, in write_event
    event.write_to(self._out)
  File "/opt/splunk/etc/apps/amp4e_events_input/bin/splunklib/modularinput/event.py", line 107, in write_to
    stream.flush()
IOError: [Errno 32] Broken pipe

**Comment by samsonnguyen** [comment] 2019-06-21 18:13
Looks to be a duplicate of #5

**Closed as completed** 2019-06-21 18:13 UTC
Labels: duplicate
