### ISSUE TITLE
input controls on configure new inputs all disabled - 1.1.0 / splunk 6.6.1

### ISSUE THREAD

**Issue by pmeyerson** [Cisco-AMP/amp4e_splunk_events_input#1] opened 2017-10-24 17:25 UTC
When I navigate to the New Input page in amp4e, all of the inbox boxes are grayed out or display the no symbol when i mouse over them, regardless of browser.

I see many entries like this in the web server log.

INFO	 error:133 - Masking the original 404 message: 'The path '/en-US/custom/amp4e_events_input/amp_streams_api_controller/groups_list' was not found.' with 'Page not found!' for security reasons
INFO	 error:133 - Masking the original 404 message: 'The path '/en-US/custom/amp4e_events_input/amp_streams_api_controller/event_types_list' was not found.' with 'Page not found!' for security reasons
INFO	 error:133 - Masking the original 404 message: 'The path '/en-US/custom/amp4e_events_input/amp_streams_api_controller/event_streams_list' was not found.' with 'Page not found!' for security reasons
ERROR	 custom:199 - cannot load specified module amp_streams_api_controller in app amp4e_events_input: No module named api_service

I did update my API key to be r/w, and then restarted splunk.  Anything else I can try?

**Comment by JeMunos** [comment] 2017-10-24 18:57
Please verify that the app permissions are set to global.
Additionally verify that the user that created the API key is an AMP4E admin user.
The API key needs to be read/write and created by an admin user.

**Comment by yr0** [comment] 2017-10-25 09:21
Hi @pmeyerson, looks like the interface of the app works while the back-end is totally invisible for Splunk, which is strange. 
Could you describe how you installed the app? Did you use the app from Splunkbase or inserted the app code directly into $SPLUNK_HOME/etc/apps/amp4e_events_input?

**Comment by pmeyerson** [comment] 2017-10-25 15:12
TA-cisco-amp4e is everyone read, admin write, sharing global.  Same for the amp4e CIM add-on.
API Key is read & write.
My amp console user account does not explicitly say admin, but i do see "Revoke Admin Credential" button when I look at other admin accounts.  So I think I'm an admin?

File permissions look OK.

I don't exactly remember, but it looks like I installed from splunkbase.  Not sure though.

**Comment by pmeyerson** [comment] 2017-10-25 15:17
Should I see anything running in the amp4e directory if I run ps -ef | grep python as root? (I don't).

The api key info does look like it saved correctly in /local/inputs.conf.

**Comment by yr0** [comment] 2017-10-25 15:55
Currently the app has only been tested from admin perspective with global permissions. Please confirm these things:
1) Is the app located within $SPLUNK_HOME/etc/apps/amp4e_events_input (when doing `ls` in that directory you should see dirs like `bin`, `default`, etc)?
2) Are you logged in as Splunk admin when accessing the app? 
3) On this page `https://<your-splunk-domain>/en-US/manager/permissions/launcher/apps/local/amp4e_events_input` is **Sharing for config file-only objects** set to **All apps**?

**Comment by pmeyerson** [comment] 2017-10-25 17:51
1. Yes
2. I wasn't before, but logging in as admin to splunk did not help.
3. Yes, config file-only objects set to All Apps.

I disabled both amp add-on/apps, deleted their directory in apps, restarted splunk, and reinstalled from splunk base.  Restarted splunk, entered my api key info.  Does not seem like it made a difference.  I notice the default app permissions are everyone: read+write, I'll leave it as that.  Global sharing still enabled.

Other cisco apps installed (incompatibilty?):
Splunk_CiscoSecuritySuite
Splunk_TA_cisco-asa
Splunk_TA_cisco-ise

This is my test splunk instance so I've got a bunch of other TAs and apps installed.

**Comment by samsonnguyen** [comment] 2017-10-25 18:12
From your app's host (splunk node with the app installed)

Are you able to connect to the following endpoints (assuming you are using the north american AMP4E cloud):

| host | protocol | port |
|--- |--- |---|
|api.amp.cisco.com | TCP|  443| 
|export-streaming.amp.cisco.com | TCP|  443|

A simple test is:

    nc -v <host> <port>
    nc -v api.amp.cisco.com 443

the following endpoints are for other versions of our AMP4e cloud

|region | host | protocol | port |
|--- |--- |--- |---|
|eu |api.eu.amp.cisco.com | TCP|  443| 
|eu |export-streaming.eu.amp.cisco.com | TCP|  443|
|apjc |api.apjc.amp.cisco.com | TCP|  443| 
|apjc |export-streaming.apjc.amp.cisco.com | TCP|  443|

Edit: Sorry, nevermind. reading your error, it does not seem like a connectivity issue to our api servers. We can see that the controller does not seem available to your splunk host.

**Comment by yr0** [comment] 2017-10-25 18:46
In addition to Samson's suggestion, it would be extremely helpful if you could share the file produced by diag script, which you can run from within linux shell on host where your Splunk instance is installed:
    
    $SPLUNK_HOME/bin/splunk login # Please log in with Splunk admin credentials
    $SPLUNK_HOME/bin/splunk diag --collect app:amp4e_events_input
    
The script will result in a *.tar.gz file, which will contain data that will hopefully help us figure out your issue. Please send it to amp4e_splunk_support@cisco.com

### Disclaimer
The data will include sensitive descriptive information about your server and Splunk instance setup, so please make sure you ONLY share it with Cisco representatives (using the e-mail address provided). **Please, do not post the file in this issue** as it is publicly accessible.

Thank you.

**Comment by yr0** [comment] 2017-10-26 16:09
@pmeyerson, thank you for the diag file, it helped us get closer to figuring out the problem.
We managed to reproduce the issue you are describing, however we are not 100% sure this is what blocks the app in your case. It would be terrific if you could help us by applying the fix within your environment:

In this file: 

$SPLUNK_HOME/etc/apps/amp4e_events_input/appserver/controllers/amp_streams_api_controller.py

find the line #11: 

    sys.path.append(make_splunkhome_path(["etc", "apps", "amp4e_events_input", "bin"])) 
replace it with:

    sys.path.insert(0, make_splunkhome_path(["etc", "apps", "amp4e_events_input", "bin"]))
Afterwards, please restart your Splunk instance and check if the issue persists.

Thank you!

**Comment by yr0** [comment] 2017-10-30 10:30
Turns out this fix actually worked, as indicated by the client. We will include it in upcoming release.

**Comment by samsonnguyen** [comment] 2019-06-21 18:09
this was fixed in version 1.1.1 and above of the app. Closing

**Closed as completed by samsonnguyen** 2019-06-21 18:09 UTC
Labels: bug, Upcoming Release
