### ISSUE TITLE
The search index doesn't show data

### ISSUE THREAD

**Issue by shadowpanter** [Cisco-AMP/amp4e_splunk_events_input#13] opened 2019-05-13 16:37 UTC
Hello,

We have a problem because we can't retrieve data from AMP for EndPoints cloud to splunk, before this, we corrected an issue "Cannot create input - SSLError(SSLError(IOError(2, 'No such file or directory')", but is okay right now.

Now we cannot see data and in Settings > Indexes  event count is 0 but all is working correctly, 

What can check for this? 
![Splunk error](https://user-images.githubusercontent.com/50590992/57638487-7cfaa280-7573-11e9-8969-73e5a09a8605.png)

**Comment by samsonnguyen** [comment] 2019-05-27 18:48
Duplicate of #12

**Closed as completed by samsonnguyen** 2019-05-27 18:48 UTC
