### ISSUE TITLE
Error says - Expected Parameters NOT URL Paramters

### ISSUE THREAD

**Issue by apursawalkam** [Cisco-AMP/amp4e_splunk_events_input#10] opened 2019-04-22 17:01 UTC
When I setup an input by picking an Event Type/Group from the drop down list, I see these messages in log over and over again...
----------------------------------------------------------------------------------------------------------
2019-04-22 12:02:09,864 ERROR Amp4eEvents - Consumer Error that does not look like connection failure! See the traceback below.
2019-04-22 12:02:09,865 ERROR Amp4eEvents - Traceback (most recent call last):
  File "/opt/splunk/etc/apps/amp4e_events_input/bin/util/stream_consumer.py", line 29, in run
    self._connection = pika.BlockingConnection(pika.URLParameters(self._url))
  File "/opt/splunk/etc/apps/amp4e_events_input/bin/pika/adapters/blocking_connection.py", line 373, in __init__
    stop_ioloop_on_close=False)
  File "/opt/splunk/etc/apps/amp4e_events_input/bin/pika/adapters/select_connection.py", line 91, in __init__
    on_close_callback, ioloop, stop_ioloop_on_close)
  File "/opt/splunk/etc/apps/amp4e_events_input/bin/pika/adapters/base_connection.py", line 60, in __init__
    'Expected instance of Parameters, not %r' % (parameters,))
ValueError: Expected instance of Parameters, not <URLParameters host=export-streaming.amp.cisco.com port=443 virtual_host=/ ssl=True>
--------------------------------------------------------------------------------------------------------

This is the Input..
------------------
[amp4e_events_input://Threat]
api_host = api.amp.cisco.com
api_id = xxxxxxxxxxxxxxxxxx
api_key = xxxxxxxxxxxxxxxx
event_types = xxxxxxxxxxx
event_types_names = Scan Completed With Detections (xxxxxxxxxx)
groups = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
groups_names = Server (xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx)
index = network
stream_name = Scan - Completed With Detections

**Comment by samsonnguyen** [comment] 2019-05-14 21:45
We have another instance of someone hitting this issue. This was their log output


```
9-05-14 12:11:30,056 ERROR Amp4eEvents - Consumer Error that does not look like connection failure! See the traceback below.
2019-05-14 12:11:30,058 ERROR Amp4eEvents - Traceback (most recent call last):
  File "/opt/splunk/etc/apps/amp4e_events_input/bin/util/stream_consumer.py", line 29, in run
    self._connection = pika.BlockingConnection(pika.URLParameters(self._url))
  File "/opt/splunk/etc/apps/amp4e_events_input/bin/pika/adapters/blocking_connection.py", line 373, in __init__
    stop_ioloop_on_close=False)
  File "/opt/splunk/etc/apps/amp4e_events_input/bin/pika/adapters/select_connection.py", line 91, in __init__
    on_close_callback, ioloop, stop_ioloop_on_close)
  File "/opt/splunk/etc/apps/amp4e_events_input/bin/pika/adapters/base_connection.py", line 60, in __init__
    'Expected instance of Parameters, not %r' % (parameters,))
ValueError: Expected instance of Parameters, not <URLParameters host=export-streaming.amp.cisco.com port=443 virtual_host=/ ssl=True>
```

Unfortunately, we are not able to replicate the issue on our docker or qa environments

**Comment by samsonnguyen** [comment] 2019-06-21 18:13
Duplicate of #5

**Closed as completed by samsonnguyen** 2019-06-21 18:13 UTC
