### ISSUE TITLE
Cannot create input - SSLError(SSLError(IOError(2, 'No such file or directory')

### ISSUE THREAD

**Issue by inspired** [Cisco-AMP/amp4e_splunk_events_input#12] opened 2019-05-07 13:12 UTC
I am having trouble creating my first input after configuring the app. Splunk 7.2.3

Error message:

> Warning! We couldn’t retrieve the information from API with provided credentials. Please make sure the API host is accessible or re-configure the input with correct credentials.

$SPLUNK_HOME/var/log/splunk/amp4e_events_input.log shows the following

```
2019-04-30 21:15:24,039 ERROR Amp4eEvents - SSLError(SSLError(IOError(2, 'No such file or directory'),),)
2019-04-30 21:15:24,039 ERROR Amp4eEvents - API Error (status 502): Request failure: <class 'requests.exceptions.SSLError'>
2019-04-30 21:15:24,040 ERROR Amp4eEvents - Traceback (most recent call last):
File "/opt/splunk/etc/apps/amp4e_events_input/bin/util/api_service.py", line 31, in wrapper
response = func(*args, **kwargs)
File "/opt/splunk/etc/apps/amp4e_events_input/bin/util/api_service.py", line 71, in event_types
return requests.get(self.__construct_url('', self.EVENT_TYPES_ENDPOINT), **self.__shared_options())
File "/opt/splunk/lib/python2.7/site-packages/requests/api.py", line 55, in get
return request('get', url, **kwargs)
File "/opt/splunk/lib/python2.7/site-packages/requests/api.py", line 44, in request
return session.request(method=method, url=url, **kwargs)
File "/opt/splunk/lib/python2.7/site-packages/requests/sessions.py", line 456, in request
resp = self.send(prep, **send_kwargs)
File "/opt/splunk/lib/python2.7/site-packages/requests/sessions.py", line 559, in send
r = adapter.send(request, **kwargs)
File "/opt/splunk/lib/python2.7/site-packages/requests/adapters.py", line 382, in send
raise SSLError(e, request=request)
SSLError: [Errno 2] No such file or directory
2019-04-30 21:15:24,040 ERROR Amp4eEvents - SSLError(SSLError(IOError(2, 'No such file or directory'),),)
2019-04-30 21:15:24,041 ERROR Amp4eEvents - API Error (status 502): Request failure: <class 'requests.exceptions.SSLError'>
```

Configuration parameters
- AMP for Endpoints API Host: api.eu.amp.cisco.com
- API Client ID: -o-o-o-o-
- API Key: -o-o-o-o-

The firewall is open. I am able to connect to _api.eu.amp.cisco.com_ with openssl from the command line from the same host.

**Comment by frbor** [comment] 2019-05-13 09:57
We had the same problem, and found that there is an error in the SSL configuration of the APP. Unfortunately, the last version of the app is not published to GitHub, however, what we saw is that the configuration tries to set a CA bundle to `/opt/splunk/openssl/cert.pem` (which does not exist).

A workaround is to hard code the SSL config in `amp4e_events_input/bin/util/api_service.py` and change

`'verify': self.__ssl_options()` to `'verify': True` under `__shared_options()`. I'm not sure where the original cert.pem file came from, as it is not configured in web.conf.

Update: when we got this to work, we got authentication errors towards api.eu.amp.cisco.com, however, it seems to work towards api.amp.cisco.com (removing `.eu`).

**Comment by inspired** [comment] 2019-05-13 10:47
Thanks a lot. This solved my issue. I am leaving this open for the developers as it looks like a bug, or something we should be able to specify in the configuration.

Note that I was able to do this towards **api.eu.amp.cisco.com**! I just had to restart the Splunk forwarder

**Comment by inspired** [comment] 2019-05-13 12:08
Adding an Input now gives the following error:

`
2019-05-13 14:07:02,679 ERROR Amp4eEvents - Consumer Error that does not look like connection failure! See the traceback below.
2019-05-13 14:07:02,680 ERROR Amp4eEvents - Traceback (most recent call last):
  File "/opt/splunk/etc/apps/amp4e_events_input/bin/util/stream_consumer.py", line 29, in run
    self._connection = pika.BlockingConnection(pika.URLParameters(self._url))
  File "/opt/splunk/etc/apps/amp4e_events_input/bin/pika/adapters/blocking_connection.py", line 373, in __init__
    stop_ioloop_on_close=False)
  File "/opt/splunk/etc/apps/amp4e_events_input/bin/pika/adapters/select_connection.py", line 91, in __init__
    on_close_callback, ioloop, stop_ioloop_on_close)
  File "/opt/splunk/etc/apps/amp4e_events_input/bin/pika/adapters/base_connection.py", line 60, in __init__
    'Expected instance of Parameters, not %r' % (parameters,))
ValueError: Expected instance of Parameters, not <URLParameters host=export-streaming.eu.amp.cisco.com port=443 virtual_host=/ ssl=True>
`

**Comment by frbor** [comment] 2019-05-15 08:04
Unfortunately we see the same error as you, and have not yet found a fix for this.

**Comment by frbor** [comment] 2019-05-15 08:33
We had a last attempt and found out that it seems to work to replace the `bin/pika` directory in the app with the `pika` directory checkout out from [https://github.com/pika/pika](https://github.com/pika/pika). 

_Cisco employees watching this repository_: It seems like the latest version of this app is not available on Github, but if it were, I could create a PR with the changes that worked for us.

**Comment by samsonnguyen** [comment] 2019-05-16 17:32
hi @frbor 
We appreciate your input. We are in the process of removing our internal repo in favor of this public one and make this truly an open sourced project. There are currently developments to move our internal dev workflow towards docker for this very reason.

**Comment by pschulze** [comment] 2019-05-30 15:31
With regards to the SSL issue, we have identified this as an incompatibility with Splunk 7.2 and are currently working on a fix.

**Comment by arock1972** [comment] 2019-06-13 05:42
Hi i am getting the same error; while attempting to create new input stream.
splunk ver. 6.6.4; machine is reachable to internet (directly) no proxy too.. 

Warning! We couldn’t retrieve the information from API with provided credentials. Please make sure the API host is accessible or re-configure the input with correct credentials.

Note: credentials verified it is correct..  curl is working no issues to retrieve from rest endpoints..

errors in /$SPLUNK_HOME/var/log/amp4e_events_ input.log
++++++++++++++++++++
2019-06-12 11:13:10,235 ERROR Amp4eEvents - SSLError(SSLError(IOError(2, 'No such file or directory'),),)
2019-06-12 11:13:10,235 ERROR Amp4eEvents - API Error (status 502): Request failure: <class 'requests.exceptions.SSLError'>
2019-06-12 11:13:10,266 ERROR Amp4eEvents - Traceback (most recent call last):
  File "/apps/splunk/etc/apps/amp4e_events_input/bin/util/api_service.py", line 31, in wrapper
    response = func(*args, **kwargs)
  File "/apps/splunk/etc/apps/amp4e_events_input/bin/util/api_service.py", line 75, in groups
    return requests.get(self.__construct_url('', self.GROUPS_ENDPOINT), **self.__shared_options())
  File "/apps/splunk/lib/python2.7/site-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/apps/splunk/lib/python2.7/site-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/apps/splunk/lib/python2.7/site-packages/requests/sessions.py", line 456, in request
    resp = self.send(prep, **send_kwargs)
  File "/apps/splunk/lib/python2.7/site-packages/requests/sessions.py", line 559, in send
    r = adapter.send(request, **kwargs)
  File "/apps/splunk/lib/python2.7/site-packages/requests/adapters.py", line 382, in send
    raise SSLError(e, request=request)
SSLError: [Errno 2] No such file or directory
++++++++++++++++++++++++++

please help..

**Comment by arock1972** [comment] 2019-06-13 05:46
1.1.4  (TA version - which i am trying)

**Comment by arock1972** [comment] 2019-06-14 03:54
Hi,
i did the workaround specified earlier 
+++++++++++++
A workaround is to hard code the SSL config in amp4e_events_input/bin/util/api_service.py and change

'verify': self.__ssl_options() to 'verify': True under __shared_options(). I'm not sure where the original cert.pem file came from, as it is not configured in web.conf.
+++++++++++++++++

now no errors; but it is NOT pulling any data...

cat amp4e_events_input.log
date  INFO Amp4eEvents - Received response from ApiService (200)
date  INFO Amp4eEvents - Received response from ApiService (200)

**Comment by samsonnguyen** [comment] 2019-06-21 18:12
We've release v1.1.5 (c3018daf99dbee07da2ca13ccf87d3135fcd51b5) of the app which should address this issue. Closing for now

**Comment by inspired** [comment] 2019-06-22 05:07
This is not fixed. I am still getting SSLError (and "could not retrieve data...") with Splunk 7.3.0 on the v1.1.5 release which I got from Splunkbase (made sure to do a clean install).

It could not find the file /opt/splunk/etc/apps/amp4e_events_input/certs/amp_cisco.crt so I pulled it from https://github.com/Cisco-AMP/amp4e_splunk_events_input/pull/14/commits/2ee51e6a9c2fc5ce48a83904f23eefc8c65fe99c and created it, which now let me create a new Input.

I am however not seeing any data in Splunk when I do a search for `index=* sourcetype=*cisco:amp:event*`

**Comment by arock1972** [comment] 2019-06-22 15:48
Hi,
looks like the issue is NOT fixed yet. Also i am trying to use this app at Heavy Forwarder, which is behind Proxy; in the previous version 1.1.4 - i was able to create stream.. but after which, no data retrieval happens.. while checking error log at /var/log/splunk/amp4_*.log  

2019-06-21 07:56:39,284 WARNING Amp4eEvents - Connection error (1561118199.28, <class 'pika.exceptions.ConnectionClosed'>: The AMQP connection was closed: ('Connection to 52.70.56.136:443 failed: timeout',))! Reconnecting in about 3 seconds
2019-06-21 07:56:54,298 WARNING Amp4eEvents - Connection error (1561118214.3, <class 'pika.exceptions.ConnectionClosed'>: The AMQP connection was closed: ('Connection to 52.70.56.136:443 failed: timeout',))! Reconnecting in about 3 seconds
2019-06-21 07:57:06,321 WARNING Amp4eEvents - Connection error (1561118226.32, <class 'pika.exceptions.ConnectionClosed'>: The AMQP connection was closed: ('Connection to 52.70.56.136:443 failed: timeout',))! Reconnecting in about 3 seconds
2019-06-21 07:57:18,344 WARNING Amp4eEvents - Connection error (1561118238.34, <class 'pika.exceptions.ConnectionClosed'>: The AMQP connection was closed: ('Connection to 52.70.56.136:443 failed: timeout',))! Reconnecting in about 3 seconds
2019-06-21 07:57:29,360 WARNING Amp4eEvents - Connection error (1561118249.36, <class 'pika.exceptions.ConnectionClosed'>: The AMQP connection was closed: ('Connection to 52.70.56.136:443 failed: timeout',))! Reconnecting in about 3 seconds
2019-06-21 07:57:42,383 WARNING Amp4eEvents - Connection error (1561118262.38, <class 'pika.exceptions.ConnectionClosed'>: The AMQP connection was closed: ('Connection to 52.70.56.136:443 failed: timeout',))! Reconnecting in about 3 seconds
2019-06-21 07:57:57,405 WARNING Amp4eEvents - Connection error (1561118277.41, <class 'pika.exceptions.ConnectionClosed'>: The AMQP connection was closed: ('Connection to 52.70.56.136:443 failed: timeout',))! Reconnecting in about 3 seconds

**Comment by samsonnguyen** [comment] 2019-06-25 13:44
Re-opened. Turns out there was a missed configuration when packaging that excluded the packaged cert from being packaged into the app. We will address this in 1.1.6

**Comment by samsonnguyen** [comment] 2019-07-05 16:04
Hello, PR #21  should solve this problem.

We've also released [v1.1.6](https://splunkbase.splunk.com/app/3670/) of our app on Splunkbase. Please give that a try and let us know if the issue still persists.

**Closed as completed by samsonnguyen** 2019-07-05 16:04 UTC

**Comment by arock1972** [comment] 2019-07-09 05:54
I don't think, the error got resolved..

My production environment:   
Splunk Heavy Forwarder : ver 6.6.4  | Cisco Amp for EP inputs APP: ver 1.1.6

Steps followed
1. removed existing 1.1.4 app (which didn't work at all)..
2. restarted Splunk enterprise
3. Installed 1.1.6 APP
4. Configuration tab -> to define api.amp.cisco.com and Client ID / API Key  (no issue)
5. Input configuration -> I can't create.. also NOT displaying existing subscribed streams
	when I click (input) getting error in next screen
     Warning! We couldn’t retrieve the information from API with provided credentials. Please make sure the API host is accessible or re-configure the input with correct credentials.
6. while checking $SPLUNK_HOME/var/log/splunk/amp4e_events_input.log, below errors.. 

+++++++++++++++++++++++++++++++++++++++++++
2019-07-09 05:40:40,348 ERROR Amp4eEvents - SSLError(SSLError(IOError(2, 'No such file or directory'),),)
2019-07-09 05:40:40,348 ERROR Amp4eEvents - API Error (status 502): Request failure: <class 'requests.exceptions.SSLError'>
2019-07-09 05:45:53,561 ERROR Amp4eEvents - Traceback (most recent call last):
  File "/apps/splunk/etc/apps/amp4e_events_input/bin/util/api_service.py", line 32, in wrapper
    response = func(*args, **kwargs)
  File "/apps/splunk/etc/apps/amp4e_events_input/bin/util/api_service.py", line 49, in index
    return requests.get(self.__construct_url(), **self.__shared_options())
  File "/apps/splunk/lib/python2.7/site-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/apps/splunk/lib/python2.7/site-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/apps/splunk/lib/python2.7/site-packages/requests/sessions.py", line 456, in request
    resp = self.send(prep, **send_kwargs)
  File "/apps/splunk/lib/python2.7/site-packages/requests/sessions.py", line 559, in send
    r = adapter.send(request, **kwargs)
  File "/apps/splunk/lib/python2.7/site-packages/requests/adapters.py", line 382, in send
    raise SSLError(e, request=request)
SSLError: [Errno 2] No such file or directory

2019-07-09 05:45:53,561 ERROR Amp4eEvents - SSLError(SSLError(IOError(2, 'No such file or directory'),),)
2019-07-09 05:45:53,561 ERROR Amp4eEvents - API Error (status 502): Request failure: <class 'requests.exceptions.SSLError'>
++++++++++++++++++++++++++++++++++++++++++++++

**Comment by pschulze** [comment] 2019-07-09 14:33
Hi @arock1972 version 1.1.6 should have resolved these file not found errors, can you please validate that `$SPLUNK_HOME/etc/apps/amp4e_events_input/certs/amp_cisco.crt` exists on your environment?

I was not able to recreate your issue locally with splunk 6.6.3 (there's no 6.6.4 docker image), from a fresh install I was able to enter in valid api credentials for api.amp.cisco.com and create an input without issues.

**Comment by arock1972** [comment] 2019-07-11 05:25
Yes, the file exists

[linux]$ pwd
/apps/splunk/etc/apps/amp4e_events_input/certs

[linux]$ ls -l
total 16
-rw-r--r-- 1 splunk splunk 14032 Jul  9 05:38 amp_cisco.crt
